# Generated by Django 2.0.5 on 2018-09-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('multiverse_id', models.CharField(max_length=100)),
                ('layout', models.CharField(max_length=100)),
                ('mana_cost', models.CharField(max_length=100)),
                ('cmc', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
                ('color_identity', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('supertypes', models.TextField()),
                ('subtypes', models.TextField()),
                ('rarity', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('flavor', models.TextField()),
                ('artist', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('toughness', models.CharField(max_length=100)),
                ('loyalty', models.CharField(max_length=100)),
                ('rulings', models.TextField()),
                ('printings', models.TextField()),
                ('legalities', models.TextField()),
                ('image_url', models.URLField(max_length=1000)),
                ('card_set', models.CharField(max_length=100)),
                ('set_name', models.TextField()),
            ],
        ),
    ]
