# Generated by Django 2.0.5 on 2018-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('multiverse_id', models.IntegerField()),
                ('layout', models.CharField(max_length=100)),
                ('mana_cost', models.CharField(max_length=100)),
                ('cmc', models.IntegerField()),
                ('colors', models.CharField(max_length=100)),
                ('color_identity', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('supertypes', models.CharField(max_length=100)),
                ('subtypes', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('flavor', models.TextField()),
                ('artist', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('power', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('loyalty', models.IntegerField()),
                ('rulings', models.TextField()),
                ('printings', models.CharField(max_length=100)),
                ('legalities', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=1000)),
                ('card_set', models.CharField(max_length=100)),
                ('set_name', models.CharField(max_length=100))
            ]
        )
    ]
