# Generated by Django 2.0.5 on 2018-09-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mtg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('competitive_format', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainboard', to='mtg.Card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainboard', to='mtg.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='SideBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sideboard', to='mtg.Card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sideboard', to='mtg.Deck')),
            ],
        ),
    ]
