# Generated by Django 2.0.5 on 2018-09-04 22:36

from django.db import migrations

def seed(apps, schema_editor):
    Card = apps.get_model('mtg', 'Card')
    
    # Fad(decade = nineties, name='JNCOs', description='JNCO, short for "Judge None Choose One", is a Los Angeles, California based clothing company specializing in boys\' and men\'s jeans.', image_url='https://img.buzzfeed.com/buzzfeed-static/static/2015-06/23/15/enhanced/webdr08/enhanced-22226-1435087265-4.jpg?downsize=715:*&output-format=auto&output-quality=auto').save()


def fallow(apps, schema_editor):
    Card = apps.get_model('mtg', 'Card')
    Card.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mtg', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
